#' Simulate longitudinal omics data for lomda
#'
#' Generates a synthetic longitudinal omics dataset for testing and
#' demonstrating the \code{lomda} two-stage pipeline. The data are generated
#' from latent longitudinal PC scores, and the observed omics features are then
#' generated from these scores through a loading matrix.
#'
#' @details
#' The simulation follows the two-stage structure used by \code{lomda}.
#' First, latent PC scores are generated from a longitudinal mixed model.
#' Then, omics features are generated from these latent scores.
#'
#' Let \eqn{i = 1, \ldots, N} index subjects,
#' \eqn{j = 1, \ldots, M_i} index the observed visits for subject \eqn{i},
#' and \eqn{k = 1, \ldots, K} index latent PCs.
#' Let \eqn{\mathrm{age}_{ij}} denote the age of subject \eqn{i} at visit
#' \eqn{j}.
#'
#' The first latent PC score contains an age effect:
#' \deqn{
#' t_{ij1} = \beta_{01} + \beta_{11}\mathrm{age}_{ij} + b_i + g_{ij1},
#' }
#' where \eqn{b_i \sim N(0, \sigma_b^2)} is a subject-specific random
#' intercept and \eqn{g_{ij1} \sim N(0, \sigma_t^2)} is visit-level noise.
#'
#' The remaining latent PC scores are generated as noise components:
#' \deqn{
#' t_{ijk} = g_{ijk}, \quad k = 2, \ldots, K,
#' }
#' where \eqn{g_{ijk} \sim N(0, \sigma_t^2)}.
#'
#' The observed omics features are generated by
#' \deqn{
#' x_{ijm} = \mu_m + \sum_{k = 1}^{K} t_{ijk} w_{mk} + \epsilon_{ijm},
#' }
#' for features \eqn{m = 1, \ldots, p}, where \eqn{w_{mk}} are feature
#' loadings and \eqn{\epsilon_{ijm} \sim N(0, \sigma_e^2)} is measurement
#' error.
#'
#' Therefore, the longitudinal age effect is embedded in the latent PC score,
#' rather than directly in each omics feature. This mirrors the intended
#' \code{lomda} workflow: PCA is first applied to the omics matrix, and the
#' estimated PC scores are then modelled longitudinally.
#'
#' @param n_subjects Integer. Number of subjects. Default \code{50}.
#' @param n_visits Integer. Maximum number of visits per subject. Default
#'   \code{3}.
#' @param n_features Integer. Number of omics features. Default \code{50}.
#' @param n_pc Integer. Number of latent PCs used to generate the data.
#'   Default \code{3}.
#' @param age_effect Numeric. Effect of age on the first latent PC.
#'   Default \code{0.05}.
#' @param sigma_b Numeric. Standard deviation of the subject-level random
#'   intercept. Default \code{1.5}.
#' @param sigma_t Numeric. Standard deviation of latent score noise.
#'   Default \code{1}.
#' @param sigma_e Numeric. Standard deviation of omics measurement error.
#'   Default \code{1}.
#' @param missing_visit_prob Numeric between 0 and 1. Probability that a
#'   non-baseline visit is removed. Default \code{0}.
#' @param seed Integer. Random seed for reproducibility. Default \code{2026}.
#'
#' @return A data frame with columns:
#' \describe{
#'   \item{\code{ID}}{Subject identifier.}
#'   \item{\code{visit}}{Observed visit number.}
#'   \item{\code{age}}{Age at visit.}
#'   \item{\code{M1}, \code{M2}, ...}{Simulated omics feature values.}
#' }
#'
#' @examples
#' dat <- simulate_lomda_data(
#'   n_subjects = 30,
#'   n_visits = 3,
#'   n_features = 20,
#'   n_pc = 3,
#'   missing_visit_prob = 0.2,
#'   seed = 1
#' )
#'
#' dim(dat)
#' head(dat[, 1:7])
#'
#' @export
simulate_lomda_data <- function(n_subjects = 50,
                                n_visits = 3,
                                n_features = 50,
                                n_pc = 3,
                                age_effect = 0.05,
                                sigma_b = 1.5,
                                sigma_t = 1.0,
                                sigma_e = 1.0,
                                missing_visit_prob = 0,
                                seed = 2026) {

  set.seed(seed)

  if (n_pc > n_features) {
    stop("n_pc cannot exceed n_features.")
  }

  if (missing_visit_prob < 0 || missing_visit_prob >= 1) {
    stop("missing_visit_prob must be in [0, 1).")
  }

  subject_ids <- sprintf("S%03d", seq_len(n_subjects))

  baseline_age <- rnorm(n_subjects, mean = 45, sd = 10)
  rand_int <- rnorm(n_subjects, mean = 0, sd = sigma_b)

  mu <- rnorm(n_features, mean = 0, sd = 2)

  W_raw <- matrix(
    rnorm(n_features * n_pc),
    nrow = n_features,
    ncol = n_pc
  )

  W <- qr.Q(qr(W_raw))

  feature_names <- paste0("M", seq_len(n_features))

  rows <- list()
  idx <- 1L

  for (i in seq_len(n_subjects)) {

    visits_i <- seq_len(n_visits)

    if (n_visits > 1 && missing_visit_prob > 0) {
      keep <- c(
        TRUE,
        stats::runif(n_visits - 1) > missing_visit_prob
      )
      visits_i <- visits_i[keep]
    }

    for (j in visits_i) {

      age_ij <- baseline_age[i] + 2 * (j - 1)

      t_ij <- numeric(n_pc)

      t_ij[1] <- age_effect * age_ij +
        rand_int[i] +
        stats::rnorm(1, mean = 0, sd = sigma_t)

      if (n_pc > 1) {
        t_ij[2:n_pc] <- stats::rnorm(n_pc - 1, mean = 0, sd = sigma_t)
      }

      epsilon <- stats::rnorm(n_features, mean = 0, sd = sigma_e)

      omics <- as.numeric(mu + W %*% t_ij + epsilon)

      rows[[idx]] <- c(
        list(
          ID = subject_ids[i],
          visit = j,
          age = age_ij
        ),
        stats::setNames(as.list(omics), feature_names)
      )

      idx <- idx + 1L
    }
  }

  dplyr::bind_rows(rows)
}
